### ISSUE TITLE
Plz add support for lsp server

### ISSUE THREAD

**Issue by Gul7333** [deadlyjack/Acode#881] opened 2023-11-06 06:58 UTC
Add lsp server support....
Now command line tool like helix editor and neovim support lsp ,,but acode doesn't...
It is must feature....
Plz add It asap

**Comment by HoldYourWaffle** [comment] 2024-01-10 18:46
Probably a (disrespectful) duplicate of #339.

**Closed** 2024-10-13 04:44 UTC
