### ISSUE TITLE
Bug; google keyboard; no toolbar in acode;

### ISSUE THREAD

**Issue by marko090591** [deadlyjack/Acode#947] opened 2024-03-17 13:55 UTC
Hello

I have found a bug. There is no option for additional ribbon in acode. Verson of google keyboard is listed bellow. Please fix it. Thank you

 
No ribbon in acode
![1000005069-1](https://github.com/deadlyjack/Acode/assets/52610785/2be0cf66-03bc-4918-a2f9-babaa7254ad5)

Ribbon which is missing in acode
![1000005071-1](https://github.com/deadlyjack/Acode/assets/52610785/7e4f23de-8cde-4a4a-8f54-2315f03856ee)

Version of acode
![1000005072-1](https://github.com/deadlyjack/Acode/assets/52610785/e84033c5-e954-4fe5-8c1b-af71c2898834)

**Comment by zhanbao2000** [comment] 2024-05-02 04:15
same issue in 1.10.1 (946)

**Comment by ByteJoseph** [comment] 2024-05-24 11:50
That's not a bug

**Comment by ByteJoseph** [comment] 2024-05-24 11:56
You can enable that feature in settings.

Watch this video and try 👇
🚨 Close the issue 
https://github.com/deadlyjack/Acode/assets/131424720/95e90275-3546-44fe-b354-68ec7ebbeeba

**Closed** 2024-05-25 19:02 UTC
